### ISSUE TITLE
Commit phase - Test&Package failing 

### ISSUE THREAD

**Issue by ciseburg** [stelligent/dromedary-serverless#5]
Hi there,

I tried using this demo, but notice a failure during packaging phase of the code pipeline. here is the error detail... would appreciate any pointers on how to proceed. Thanks 

2016-09-15T17:48:31.930Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Downloading input artifact 'SourceInstalledOutput' to '/tmp/source_installed.tar.gz'
2016-09-15T17:48:31.930Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Getting S3 Object 'dromedary-serverless-pipelinestack-artifactbucket-4kqh6sxacb4s/dromedary-serverless/SourceInst/4MeRzVc' to '/tmp/source_installed.tar.gz'
2016-09-15T17:48:32.286Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Cleaning directory '/tmp/source_installed/'
2016-09-15T17:48:32.292Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Extracting tarball '/tmp/source_installed.tar.gz' to '/tmp/source_installed/'
2016-09-15T17:49:01.520Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Installing npm into '/tmp/source_installed/'
2016-09-15T17:49:01.832Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Running gulp task 'package' in '/tmp/source_installed/'
2016-09-15T17:49:01.832Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    PATH: /usr/local/bin:/usr/bin/:/bin:/tmp/source_installed//node_modules/.bin/

path.js:313
throw new TypeError('Arguments to path.resolve must be strings');
^
TypeError: Arguments to path.resolve must be strings
at Object.exports.resolve (path.js:313:15)
at Object.<anonymous> (/tmp/source_installed/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/resolve-dir/node_modules/global-modules/node_modules/global-prefix/index.js:21:25)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/tmp/source_installed/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/resolve-dir/node_modules/global-modules/index.js:11:14)
at Module._compile (module.js:456:26)
2016-09-15T17:49:01.999Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Prior attempts=0 and retrys=0
2016-09-15T17:49:01.999Z    9d74cacb-7b6c-11e6-96bb-3f0d6e4d1108    Failure: "Error(8) - path.js:313\n throw new TypeError('Arguments to path.resolve must be strings');\n ^\nTypeError: Arguments to path.resolve must be strings\n at Object.exports.resolve (path.js:313:15)\n at Object.<anonymous> (/tmp/source_installed/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/resolve-dir/node_modules/global-modules/node_modules/global-prefix/index.js:21:25)\n at Module._compile (module.js:456:26)\n at Object.Module._extensions..js (module.js:474:10)\n at Module.load (module.js:356:32)\n at Function.Module._load (module.js:312:12)\n at Module.require (module.js:364:17)\n at require (module.js:380:17)\n at Object.<anonymous> (/tmp/source_installed/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/resolve-dir/node_modules/global-modules/index.js:11:14)\n at Module._compile (module.js:456:26)\n"

**Comment by ciseburg** [comment]
Ping

**Comment by cplee** [comment]
I suspect problem showed up after moving to latest version of nodejs(4.3) in lambda.  I've reverted and will research issue,  but in meantime feel free to try again with latest from master.

**Comment by krcummings1** [comment]
Experiencing the same issue. @cplee find any resolution?

**Comment by davidsulpy** [comment]
@cplee the issue also seems to happen even with latest using the legacy NodeJS (0.10) runtime in lambda as opposed to nodejs4.3.

**Comment by davidsulpy** [comment]
Btw, I've gotten past this error in my CodePipelineGulpLambda function by changing the nodejs runtime TO nodejs4.3 actually. Now I have a separate issue which is:

```
2016-10-26T18:09:06.840Z    0bfbe5b6-9ba7-11e6-b9fb-45e34bb6151c    cmd: node /tmp/source_installed/node_modules/gulp/bin/gulp.js --no-color package opts: { cwd: '/tmp/source_installed/', env: { PATH: '/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin:/tmp/source_installed/node_modules/.bin/', LAMBDA_TASK_ROOT: '/var/task', LAMBDA_RUNTIME_DIR: '/var/runtime', AWS_REGION: 'us-west-2', AWS_DEFAULT_REGION: 'us-west-2', AWS_LAMBDA_LOG_GROUP_NAME: '/aws/lambda/dromedary-serverless-Pipeli-CodePipelineGulpLambda-1B5WBBSOTTR2G', AWS_LAMBDA_LOG_STREAM_NAME: '2016/10/26/[$LATEST]6c02319409e5435da01f34e6cdd5b904', AWS_LAMBDA_FUNCTION_NAME: 'dromedary-serverless-Pipeli-CodePipelineGulpLambda-1B5WBBSOTTR2G', AWS_LAMBDA_FUNCTION_MEMORY_SIZE: '1536', AWS_LAMBDA_FUNCTION_VERSION: '$LATEST', LANG: 'en_US.UTF-8', LD_LIBRARY_PATH: '/usr/local/lib64/node-v4.3.x/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib', NODE_PATH: '/var/runtime:/var/task:/var/runtime/node_modules', AWS_ACCESS_KEY_ID: '***', AWS_SECRET_ACCESS_KEY: '***', AWS_SESSION_TOKEN: '***' } }
2016-10-26T18:09:06.853Z    0bfbe5b6-9ba7-11e6-b9fb-45e34bb6151c    I've gotten here
[18:09:08] Using gulpfile /tmp/source_installed/gulpfile.js
[18:09:08] Starting 'lint-charthandler'...
[18:09:08] Starting 'lint-app'...
[18:09:08] Starting 'test'...
test task
[18:09:08] Starting 'dist-app'...
dist-app task
[18:09:08] Starting 'package-swagger'...


inMemoryStorage
.getForChartJs()
[18:09:08] Finished 'lint-charthandler' after 289 ms
[18:09:08] Starting 'package-site'...
package-site task
✓ has exactly 3 items
[18:09:08] Finished 'package-swagger' after 360 ms
✓ each item has exactly 4 properties
✓ each item has properties: value,color,highlight,label
[18:09:08] Finished 'lint-app' after 454 ms
.getAllCounts()
✓ has exactly 3 items
[18:09:08] Finished 'package-site' after 190 ms
✓ each item is a number
.incrementCount()
✓ increments counts by one
.colorExists()
✓ each color exists
✓ bad colors do not exist

requestThrottle
.logIp()
✓ adds ip to map
.checkIp()
✓ does throttle mapped ip
✓ does not throttle mapped ip after blackoutPeriod
✓ does not throttle unmapped ip
.gcMap()
Deleted ip from throttle map: 127.0.0.2
✓ removes expired ip
Deleted ip from throttle map: 127.0.0.2
✓ does not remove unexpired ip


14 passing (407ms)

[18:09:08] Finished 'test' after 470 ms
npm WARN package.json dromedary@0.1.0 No README data
npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/local/lib64/node-v4.3.x/bin/node" "/usr/local/lib64/node-v4.3.x/bin/npm" "install" "--production"
npm ERR! node v4.3.2
npm ERR! npm v2.14.12
npm ERR! path /home/sbx_user1051
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir

npm ERR! rofs EROFS: read-only file system, mkdir '/home/sbx_user1051'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/source_installed/dist/app/npm-debug.log
[18:09:09] npm exited with non-zero code 226 , run `npm install --production` manually
[18:09:09] 'dist-app' errored after 1.37 s
[18:09:09] Error: npm exited with non-zero code 226
at ChildProcess.<anonymous> (/tmp/source_installed/node_modules/gulp-install/lib/commandRunner.js:14:19)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:821:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2016-10-26T18:09:09.459Z    0bfbe5b6-9ba7-11e6-b9fb-45e34bb6151c    Prior attempts=0 and retrys=0
2016-10-26T18:09:09.459Z    0bfbe5b6-9ba7-11e6-b9fb-45e34bb6151c    Failure: "Error(1) - Error: npm exited with non-zero code 226\n at ChildProcess.<anonymous> (/tmp/source_installed/node_modules/gulp-install/lib/commandRunner.js:14:19)\n at emitTwo (events.js:87:13)\n at ChildProcess.emit (events.js:172:7)\n at maybeClose (internal/child_process.js:821:16)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)\n"
2016-10-26T18:09:09.648Z    0bfbe5b6-9ba7-11e6-b9fb-45e34bb6151c
{
    "errorMessage": "\"Error(1) - Error: npm exited with non-zero code 226\\n    at ChildProcess.<anonymous> (/tmp/source_installed/node_modules/gulp-install/lib/commandRunner.js:14:19)\\n    at emitTwo (events.js:87:13)\\n    at ChildProcess.emit (events.js:172:7)\\n    at maybeClose (internal/child_process.js:821:16)\\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)\\n\""
}
```

**Comment by cplee** [comment]
@ciseburg @krcummings1 @davidsulpy went back to nodejs4.3 and was able to fix the issue by setting HOME to /tmp to allow newer version of npm write cache.  Should be fixed now!
